export default {
  breakpoints: ["40em", "52em", "64em"],
  fontSizes: [12, 14, 16, 20, 24, 32, 48, 64],
  colors: {
    text: "#CACDCE",
    lightgray: "#f6f6ff",
    border: " #a3a3a3",
    secondaryBg: "#F5F5F5",
    blue: "#07c",
  },
  space: [0, 4, 8, 16, 32, 64, 128, 256],
  fonts: {
    body: "Barlow Condensed",
    heading: "Barlow Condensed",
    monospace: "Menlo, monospace",
  },
  fontWeights: {
    light: 100,
    body: 400,
    heading: 700,
    lightbold: 600,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.25,
  },
  shadows: {
    small: "0 0 4px rgba(0, 0, 0, .125)",
    large: "0 0 24px rgba(0, 0, 0, .125)",
  },
  variants: {},
  text: {
    title: {
      fontFamily: "body",
      fontSize: "2",
      fontWeight: "light",
      color: "dashboardText",
      px: "3",
    },
    date: {
      fontFamily: "body",
      fontSize: "5",
      fontWeight: "heading",
      color: "dashboardText",
      px: "3",
    },
    price: {
      fontFamily: "body",
      fontSize: "5",
      fontWeight: "light",
      color: "dashboardText",
      px: "3",
    },
    name: {
      fontFamily: "body",
      fontSize: "2",
      fontWeight: "body",
      color: "gray",
      px: "3",
    },
    subtitle: {
      fontFamily: "body",
      fontSize: "4",
      fontWeight: "body",
      color: "dashboardText",
      px: "3",
      pb: "2",
    },
  },
  buttons: {
    primary: {
      color: "gray",
      bg: "transparent",
      ":hover": { color: "#3F3F3F" },
      fontFamily: "body",
      fontWeight: "body",
      borderRadius: "0px",
    },
    sizebutton: {
      color: "black",
      bg: "white",
      ":hover": { color: "#3F3F3F" },
      fontFamily: "body",
      fontWeight: "light",
      fontSize: "2",
      borderRadius: "0px",
    },
    linkbutton: {
      bg: "blue",
      color: "white",
      ":hover": { color: "black" },
      fontWeight: "lightbold",
      fontFamily: "body",
      fontSize: "2",
      borderRadius: "0px",
    },
    borderButton: {
      border: "1px solid",
      borderColor: "border",
      borderRadius: "0px",
      color: "black",
      fontFamily: "body",
      fontWeight: "light",
    },
  },
  forms: {
    input: {
      color: "black",
      borderColor: "border",
      borderRadius: 0,
      bg: "transparent",
      fontSize: "1",
      fontFamily: "body",
      fontWeight: "body",
      //py: "10px",
      "::placeholder": { color: "lightgray" },
      ":focus": { outline: "none" },
    },
    select: {
      fontFamily: "body",
      fontWeight: "heading",
      fontSize: "1",
      color: "text",
      borderRadius: "5px",
      border: "1px solid",
      borderColor: "border",
    },
    textarea: {},
    label: {
      fontFamily: "body",
      fontWeight: "heading",
      fontSize: "1",
      color: "text",
      py: "1",
      textTransform: "uppercase",
    },
    radio: {},
    checkbox: {},
    labelSecond: {
      fontFamily: "body",
      fontWeight: "heading",
      fontSize: "1",
      color: "text",
      py: "1",
      textTransform: "capitalize",
    },
  },
};
